### ISSUE TITLE
Bug: Socket.io client connects initially but then loses connection and does not reconnect

### ISSUE THREAD

**Issue by bfla** [buccaneerai/rxws#1]
```
> let ws$ = ws({url: 'localhost:3002', topics: ['time', 'i am client', 'welcome']});
undefined
> ws$.subscribe(console.log, console.log, console.log)
{ type: 'messages/NEW',
  data: { topic: 'time', message: undefined } }
{ type: 'messages/NEW',
  data: { topic: 'i am client', message: undefined } }
{ type: 'messages/NEW',
  data: { topic: 'welcome', message: undefined } }
Subscriber {
  closed: false,
  _parentOrParents: null,
  _subscriptions: null,
  syncErrorValue: null,
  syncErrorThrown: false,
  syncErrorThrowable: true,
  isStopped: false,
  destination:
   SafeSubscriber {
     closed: false,
     _parentOrParents: null,
     _subscriptions: null,
     syncErrorValue: null,
     syncErrorThrown: false,
     syncErrorThrowable: false,
     isStopped: false,
     destination:
      { closed: true,
        next: [Function: next],
        error: [Function: error],
        complete: [Function: complete] },
     _parentSubscriber: [Circular],
     _context: [Circular],
     _next: [Function: bound consoleCall],
     _error: [Function: bound consoleCall],
     _complete: [Function: bound consoleCall] } }
> { error:
   { Error: xhr poll error
       at XHR.Transport.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transport.js:68:13)
       at Request.<anonymous> (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:131:10)
       at Request.Emitter.emit (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/component-emitter/index.js:133:20)
       at Request.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:313:8)
       at Timeout._onTimeout (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:260:18)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) type: 'TransportError', description: 503 },
  type: 'connections/ERROR' }
{ type: 'connections/RECONNECT',
  data: { attemptNumber: { attemptNumber: 1 } } }
{ type: 'connections/RECONNECTING',
  data: { attemptNumber: undefined } }
{ error:
   { Error: xhr poll error
       at XHR.Transport.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transport.js:68:13)
       at Request.<anonymous> (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:131:10)
       at Request.Emitter.emit (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/component-emitter/index.js:133:20)
       at Request.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:313:8)
       at Timeout._onTimeout (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:260:18)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) type: 'TransportError', description: 503 },
  type: 'connections/ERROR' }
{ error:
   { Error: xhr poll error
       at XHR.Transport.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transport.js:68:13)
       at Request.<anonymous> (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:131:10)
       at Request.Emitter.emit (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/component-emitter/index.js:133:20)
       at Request.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:313:8)
       at Timeout._onTimeout (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:260:18)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) type: 'TransportError', description: 503 },
  type: 'connections/RECONNECT_ERROR' }
{ type: 'connections/RECONNECT',
  data: { attemptNumber: { attemptNumber: 2 } } }
{ type: 'connections/RECONNECTING',
  data: { attemptNumber: undefined } }
{ error:
   { Error: xhr poll error
       at XHR.Transport.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transport.js:68:13)
       at Request.<anonymous> (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:131:10)
       at Request.Emitter.emit (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/component-emitter/index.js:133:20)
       at Request.onError (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:313:8)
       at Timeout._onTimeout (/Users/bfla/Documents/dev/buccaneer/opensource/rxws/node_modules/engine.io-client/lib/transports/polling-xhr.js:260:18)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) type: 'TransportError', description: 503 },
  type: 'connections/ERROR' }
```

**Comment by bfla** [comment]
✅ resolved
